/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003824",
        "on-secondary-fixed": "#002113",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "#2d3449",
        "on-primary": "#002e6a",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-container": "#5c0008",
        "primary-fixed-dim": "#adc6ff",
        "secondary-container": "#00a572",
        "surface": "#0b1326",
        "on-error-container": "#ffdad6",
        "surface-dim": "#0b1326",
        "secondary-fixed-dim": "#4edea3",
        "surface-bright": "#31394d",
        "on-primary-container": "#00285d",
        "on-surface-variant": "#c2c6d6",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#ff5451",
        "on-error": "#690005",
        "surface-container": "#171f33",
        "primary": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "secondary": "#4edea3",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#4d8eff",
        "inverse-primary": "#005ac2",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#68000a",
        "surface-container-low": "#131b2e",
        "surface-tint": "#adc6ff",
        "on-tertiary-fixed": "#410004",
        "on-surface": "#dae2fd",
        "on-background": "#dae2fd",
        "outline": "#8c909f",
        "outline-variant": "#424754",
        "surface-container-high": "#222a3d",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#930013",
        "tertiary": "#ffb3ad",
        "surface-variant": "#2d3449",
        "inverse-on-surface": "#283044",
        "tertiary-fixed": "#ffdad7",
        "background": "#0b1326"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "gutter": "16px",
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "base": "4px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "mono-data": ["Geist Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "mono-data": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
